version: "3.9"

services:
  binarykeeda-loginui:
    build:
      context: .
      args:
        VITE_PORT: ${VITE_PORT}
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_MESSAGE_QUEUE_URL: ${VITE_MESSAGE_QUEUE_URL}
        VITE_CODE_EXECUTION_API: ${VITE_CODE_EXECUTION_API}
        VITE_PAYMENT_KEY: ${VITE_PAYMENT_KEY}
        VITE_PAYMENT_URL: ${VITE_PAYMENT_URL}
        VITE_GOOGLE_CLIENT_ID: ${VITE_GOOGLE_CLIENT_ID}
        VITE_MODE: ${VITE_MODE}

    ports:
      - "5175:80"

    restart: unless-stopped
